### ISSUE TITLE
AttributeError: 'MainModel' object has no attribute 'yt_dir_listener'

### ISSUE THREAD

**Issue by skandix** [BluABK/sane-subfeed#26]
Python 3.7 
running in a virutalenv with pipenv
OS: Debian GNU/Linux testing (buster)
Release:	testing

happens with provided "public" key and with my own.. 
```
(sane-subfeed-0xji7CGb) gaupe:~/gitclone/sane-subfeed@master✗✗✗✗✗✗ skandix λ python -m sane_yt_subfeed
2018-10-02 15:51:24,872 - sane_yt_subfeed.cli - CRITICAL - Intercepted Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/__main__.py", line 8, in <module>
    cli()
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/cli.py", line 69, in cli
    run_with_gui()
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/main.py", line 33, in run_with_gui
    controller.run()
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/controller/controller.py", line 44, in run
    window = MainWindow(app, model)
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/gui/main_window/main_window.py", line 94, in __init__
    self.init_ui()
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/gui/main_window/main_window.py", line 176, in init_ui
    self.add_submenu('&Function', 'Manual dir search', self.main_model.yt_dir_listener.manualCheck.emit,
AttributeError: 'MainModel' object has no attribute 'yt_dir_listener'
2018-10-02 15:51:24,872 - sane_yt_subfeed.cli - CRITICAL - Intercepted Exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/__main__.py", line 8, in <module>
    cli()
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/cli.py", line 69, in cli
    run_with_gui()
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/main.py", line 33, in run_with_gui
    controller.run()
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/controller/controller.py", line 44, in run
    window = MainWindow(app, model)
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/gui/main_window/main_window.py", line 94, in __init__
    self.init_ui()
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/gui/main_window/main_window.py", line 176, in init_ui
    self.add_submenu('&Function', 'Manual dir search', self.main_model.yt_dir_listener.manualCheck.emit,
AttributeError: 'MainModel' object has no attribute 'yt_dir_listener'
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/__main__.py", line 8, in <module>
    cli()
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skandix/.local/share/virtualenvs/sane-subfeed-0xji7CGb/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/cli.py", line 69, in cli
    run_with_gui()
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/main.py", line 33, in run_with_gui
    controller.run()
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/controller/controller.py", line 44, in run
    window = MainWindow(app, model)
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/gui/main_window/main_window.py", line 94, in __init__
    self.init_ui()
  File "/home/skandix/gitclone/sane-subfeed/sane_yt_subfeed/gui/main_window/main_window.py", line 176, in init_ui
    self.add_submenu('&Function', 'Manual dir search', self.main_model.yt_dir_listener.manualCheck.emit,
AttributeError: 'MainModel' object has no attribute 'yt_dir_listener'
```

**Comment by BluABK** [comment]
Added working Pipfile and lock to master branch in commit 7d2570cd3387. Try using that. 

I'm not sure why `yt_dir_listener` is failing (of all things), it worked fine when I set it up on my Linux system just now.

OS: Archlinux (Antergos)
Python: 3.7.0
Pipenv: 2018.7.1
