### ISSUE TITLE
DownloadTile ETA raises IndexError: list index out of range

### ISSUE THREAD

**Issue by BluABK** [BluABK/sane-subfeed#36]
Not a critical issue, but I'll add some debug logging to check what exactly is happening.

```
Traceback (most recent call last):
  File "$HOME/git/sane-subfeed/sane_yt_subfeed/gui/views/download_view/download_tile.py", line 339, in update_progress
    self.most_common_eta(event["_eta_str"])
  File "$HOME/git/sane-subfeed/sane_yt_subfeed/gui/views/download_view/download_tile.py", line 276, in most_common_eta
    self.common_eta_str = Counter(self.etas).most_common(1)[0][0]
IndexError: list index out of range
```

**Comment by BluABK** [comment]
Finally got a hit on debug logging:

Message:
```
Unexpected IndexError in most_common_eta(time_str==02:50, ticks=50), self.etas on next line:
[]
```
Traceback:
```
Traceback (most recent call last):
  File "$HOME/git/sane-subfeed/sane_yt_subfeed/gui/views/download_view/download_tile.py", line 277, in most_common_eta
    self.common_eta_str = Counter(self.etas).most_common(1)[0][0]
IndexError: list index out of range
```
